services:
  mysql:
    image: mysql:8.4
    container_name: library-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: library
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./library.sql:/docker-entrypoint-initdb.d/library.sql

  phpmyadmin:
    image: phpmyadmin
    container_name: library-phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8090:80"

volumes:
  mysql-data: