# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: library.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'library.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\nlibrary.v1\"l\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tauthor_id\x18\x03 \x01(\x05\x12\x1d\n\x15publishing_company_id\x18\x04 \x01(\x05\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"%\n\x12GetBookByIdRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\"m\n\x11\x43reateBookRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tauthor_id\x18\x02 \x01(\x05\x12\x1d\n\x15publishing_company_id\x18\x03 \x01(\x05\x12\x17\n\x0fpublishing_year\x18\x04 \x01(\x05\"%\n\x12\x43reateBookResponse\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\"\x13\n\x11WatchBooksRequest2\xdf\x01\n\x0eLibraryService\x12?\n\x0bGetBookById\x12\x1e.library.v1.GetBookByIdRequest\x1a\x10.library.v1.Book\x12K\n\nCreateBook\x12\x1d.library.v1.CreateBookRequest\x1a\x1e.library.v1.CreateBookResponse\x12?\n\nWatchBooks\x12\x1d.library.v1.WatchBooksRequest\x1a\x10.library.v1.Book0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=29
  _globals['_BOOK']._serialized_end=137
  _globals['_GETBOOKBYIDREQUEST']._serialized_start=139
  _globals['_GETBOOKBYIDREQUEST']._serialized_end=176
  _globals['_CREATEBOOKREQUEST']._serialized_start=178
  _globals['_CREATEBOOKREQUEST']._serialized_end=287
  _globals['_CREATEBOOKRESPONSE']._serialized_start=289
  _globals['_CREATEBOOKRESPONSE']._serialized_end=326
  _globals['_WATCHBOOKSREQUEST']._serialized_start=328
  _globals['_WATCHBOOKSREQUEST']._serialized_end=347
  _globals['_LIBRARYSERVICE']._serialized_start=350
  _globals['_LIBRARYSERVICE']._serialized_end=573
# @@protoc_insertion_point(module_scope)
