spring.application.name=soap-api

spring.webservices.wsdl-locations=classpath:META-INF/schemas

spring.datasource.url=jdbc:sqlite:soap-api/src/main/resources/library.db
spring.datasource.driver-class-name=org.sqlite.JDBC
